project:
  type: website
  output-dir: docs

website:
  title: "<img src='images/NPS_Logo.png' style='height:38px; vertical-align:middle; margin-right:8px;'> <img src='images/ROSS_Logo_Vertical_White.png' style='height:38px; vertical-align:middle; margin-right:12px;'> <span style='vertical-align:middle;'>NPS Public Water Systems Analysis</span>"
  
  navbar:
    left:
      - href: NPS_PWS.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show R Code"

execute:
  warning: false
  message: false